IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDROOT_OIL]') AND type in (N'U'))
DROP TABLE [dbo].[PDROOT_OIL]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDREMARK]') AND type in (N'U'))
DROP TABLE [dbo].[PDREMARK]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDORPTCY]') AND type in (N'U'))
DROP TABLE [dbo].[PDORPTCY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDORMVDS]') AND type in (N'U'))
DROP TABLE [dbo].[PDORMVDS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOPRVAL]') AND type in (N'U'))
DROP TABLE [dbo].[PDOPRVAL]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOPRPV]') AND type in (N'U'))
DROP TABLE [dbo].[PDOPRPV]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOPROD]') AND type in (N'U'))
DROP TABLE [dbo].[PDOPROD]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOOEB]') AND type in (N'U'))
DROP TABLE [dbo].[PDOOEB]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDODSPRK]') AND type in (N'U'))
DROP TABLE [dbo].[PDODSPRK]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDODSP]') AND type in (N'U'))
DROP TABLE [dbo].[PDODSP]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOCSHDS]') AND type in (N'U'))
DROP TABLE [dbo].[PDOCSHDS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOCMPV]') AND type in (N'U'))
DROP TABLE [dbo].[PDOCMPV]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOCMPRD]') AND type in (N'U'))
DROP TABLE [dbo].[PDOCMPRD]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOCMPMT]') AND type in (N'U'))
DROP TABLE [dbo].[PDOCMPMT]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOCMODS]') AND type in (N'U'))
DROP TABLE [dbo].[PDOCMODS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDOCMGRK]') AND type in (N'U'))
DROP TABLE [dbo].[PDOCMGRK]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDGRPTCY]') AND type in (N'U'))
DROP TABLE [dbo].[PDGRPTCY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PDGPROD]') AND type in (N'U'))
DROP TABLE [dbo].[PDGPROD]
GO
CREATE TABLE [dbo].[PDGPROD](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_GAS_PROD] [decimal](20, 0) NULL,
	[PD_GAS_LIFT_GAS_INJECTED] [decimal](20, 0) NULL,
	[PD_COND_PROD] [decimal](20, 0) NULL,
	[PD_GAS_BATCH_NUMBER] [char](3) NULL,
	[PD_GAS_ITEM_NUMBER] [int] NULL,
	[PD_GAS_POSTING_YEAR] [int] NULL,
	[PD_GAS_POSTING_MONTH] [int] NULL,
	[PD_GAS_POSTING_DAY] [int] NULL,
	[PD_G_REMOVED_FLARING_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_SEALED_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_H_8_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_CIRC_OIL_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_OTHER_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_CODE4_DISCREP] [char](1) NULL,
	[PD_GAS_CORRECTED_REPORT_FLAG] [char](1) NOT NULL,
	[PD_G_REMOVED_CODE_6_DISCREP] [char](1) NULL,
	[PD_GAS_FILED_BY_EDI_FLAG] [char](1) NULL,
	[PD_G_REMOVED_WELL_PROD_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_CON_EXT_L_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_CON_INSUF_DISCREP] [char](1) NULL,
	[PD_G_REMOVED_CODE_3_DISCREP] [char](1) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDGRPTCY](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_GAS_REPORT_CYCLE_KEY] [int] NOT NULL,
	[PD_GAS_BALANCING_ALLOW_AMT] [decimal](20, 0) NULL,
	[PD_GAS_BALANCING_ALLOW_CODE] [char](2) NULL,
	[PD_GAS_EXCEPTION_TWICE_ALLOW] [char](1) NULL,
	[PD_GAS_HIGHEST_DAILY_CYCLES] [int] NULL,
	[PD_GAS_EXCEPT_HIGH_DAY_AMOUNT] [decimal](20, 0) NULL,
	[PD_GAS_REDUCED_RATE] [int] NULL,
	[PD_GAS_REDUCED_RATE_CODE] [char](1) NULL,
	[PD_COND_ENDING_BALANCE] [decimal](20, 0) NULL,
	[PD_G9_INJECTION_AMOUNT] [decimal](20, 0) NULL,
	[PD_GAS_CUMU_CYCLE_STATUS] [decimal](20, 0) NULL,
	[PD_GAS_CUMULATIVE_OVERAGE] [decimal](20, 0) NULL,
	[PD_GAS_OVERAGE_TRANSFER] [decimal](20, 0) NULL,
	[PD_GAS_NO_PAST_PRODUCTION_FLAG] [char](1) NULL,
	[PD_GAS_NO_HIGHEST_DAILY_FLAG] [char](1) NULL,
	[PD_GAS_CANCEL_UNDERAGE_FLAG] [char](1) NULL,
	[PD_GAS_PAST_PRODUCTION_CYCLES] [int] NULL,
	[PD_GAS_EXCEPT_PAST_PROD_AMOUNT] [decimal](20, 0) NULL,
	[PD_LIQUID_CUMU_CYCLE_STATUS] [decimal](20, 0) NULL,
	[PD_G9_PLANT_LIQUID] [decimal](20, 0) NULL,
	[PD_G9_INJECTION_CREDIT_CODE] [char](1) NULL,
	[PD_GAS_ON_SHUT_IN_LIST_FLAG] [char](1) NULL,
	[PD_WELL_CAPABILITY] [decimal](20, 0) NULL,
	[PD_WELL_MONTHLY_CAPABILITY] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOCMGRK](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_CMG_RMK_CENTURY] [int] NULL,
	[PD_OIL_CMG_RMK_YEAR] [int] NULL,
	[PD_OIL_CMG_RMK_MONTH] [int] NULL,
	[PD_OIL_CMG_RMK_DAY] [int] NULL,
	[PD_OIL_CMG_REMARK_TEXT] [varchar](40) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOCMODS](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_OLCO_DISPOSITION_CODE] [int] NOT NULL,
	[PD_OIL_OLCO_DISPOSITION_AMT] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOCMPMT](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_COMMINGLE_DISTRICT] [int] NOT NULL,
	[PD_OIL_COMMINGLE_NUMBER] [int] NOT NULL,
	[PD_OIL_COMMINGLE_END_BALANCE] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOCMPRD](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_COMM_PRODUCTION_AMT] [decimal](20, 0) NULL,
	[PD_OLCO_REMOVED_CM_INACTV_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_NOT_SPEC_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_OUT_OF_BALANCE] [char](1) NOT NULL,
	[PD_OIL_CM_FILED_BY_EDI_FLAG] [char](1) NOT NULL,
	[PD_OIL_COMM_BATCH_NUMBER] [char](3) NULL,
	[PD_OIL_COMM_ITEM_NUMBER] [int] NULL,
	[PD_OIL_COMM_POSTING_YEAR] [int] NULL,
	[PD_OIL_COMM_POSTING_MONTH] [int] NULL,
	[PD_OIL_COMM_POSTING_DAY] [int] NULL,
	[PD_OLCO_REMOVED_LSE_SEV_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_OTHER_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_LOST_OIL_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_CIRC_OIL_DISC] [char](1) NOT NULL,
	[PD_OIL_CM_CORRECTED_RPT_FLAG] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_CODE_6_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_R_3_DISC] [char](1) NOT NULL,
	[PD_OLCO_REMOVED_NET_OIL_DISC] [char](1) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOCMPV](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_COMM_PREV_POSTING_YEAR] [int] NULL,
	[PD_OIL_COMM_PREV_POSTING_MONTH] [int] NULL,
	[PD_OIL_COMM_PREV_POSTING_DAY] [int] NULL,
	[PD_OIL_COMM_PREV_BATCH_NUMBER] [char](3) NULL,
	[PD_OIL_COMM_PREV_ITEM_NUMBER] [int] NULL,
	[PD_OIL_COMM_PREV_CHANGED_FLAG] [char](1) NULL,
	[PD_OIL_COMM_PREV_EDI_FLAG] [char](1) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOCSHDS](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_CSH_DISPOSITION_CODE] [int] NOT NULL,
	[PD_CSH_DISPOSITION_AMT] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDODSP](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_DISPOSITION_CODE] [int] NOT NULL,
	[PD_OIL_DISPOSITION_AMOUNT] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDODSPRK](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_RMK_CENTURY] [int] NULL,
	[PD_OIL_RMK_YEAR] [int] NULL,
	[PD_OIL_RMK_MONTH] [int] NULL,
	[PD_OIL_RMK_DAY] [int] NULL,
	[PD_OIL_DISP_REMARK_TEXT] [varchar](40) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOOEB](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_CM_OLDEST_EOM_BAL] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOPROD](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_CORRECTED_REPORT_FLAG] [char](1) NOT NULL,
	[PD_OIL_PRODUCTION_AMOUNT] [decimal](20, 0) NULL,
	[PD_OIL_CASINGHEAD_GAS_AMOUNT] [decimal](20, 0) NULL,
	[PD_OIL_CASINGHEAD_GAS_LIFT] [decimal](20, 0) NULL,
	[PD_OIL_BATCH_NUMBER] [char](3) NULL,
	[PD_OIL_ITEM_NUMBER] [int] NULL,
	[PD_OIL_POSTING_YEAR] [int] NULL,
	[PD_OIL_POSTING_MONTH] [int] NULL,
	[PD_OIL_POSTING_DAY] [int] NULL,
	[PD_OIL_FILED_BY_EDI_FLAG] [char](1) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOPRPV](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_PREV_POSTING_YEAR] [int] NULL,
	[PD_OIL_PREV_POSTING_MONTH] [int] NULL,
	[PD_OIL_PREV_POSTING_DAY] [int] NULL,
	[PD_OIL_PREV_BATCH_NUMBER] [char](3) NULL,
	[PD_OIL_PREV_ITEM_NUMBER] [int] NULL,
	[PD_OIL_PREV_CHANGED_FLAG] [char](1) NULL,
	[PD_OIL_PREV_FILED_BY_EDI_FLAG] [char](1) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDOPRVAL](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_ALLOW_DAILY_BBLS_HIST] [decimal](20, 0) NULL,
	[PD_GAS_LIMIT_DAILY_MCF_HIST] [decimal](20, 0) NULL,
	[PD_OIL_ALLOW_EFF_YEAR_HIST] [int] NULL,
	[PD_OIL_ALLOW_EFF_MONTH_HIST] [int] NULL,
	[PD_OIL_ALLOW_EFF_DAY_HIST] [int] NULL,
	[PD_OIL_ALLOW_ISS_YEAR_HIST] [int] NULL,
	[PD_OIL_ALLOW_ISS_MONTH_HIST] [int] NULL,
	[PD_OIL_ALLOW_ISS_DAY_HIST] [int] NULL,
	[PD_OIL_ALLOW_CYCLE_BBLS_HIST] [decimal](20, 0) NULL,
	[PD_GAS_LIMIT_CYCLE_MCF_HIST] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDORMVDS](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_O_REMOVED_CODE_6_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_R_3_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_NET_OIL_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_LSE_SEV_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_OTHER_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_LOST_OIL_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_CIRC_OIL_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_PRD_INACT_DISCREP] [char](1) NOT NULL,
	[PD_O_REMOVED_FILE_COMM_DISCREP] [char](1) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDORPTCY](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_RPT_CYCLE_KEY] [int] NOT NULL,
	[PD_DAILY_OIL_PRORATED_ALLOW] [decimal](16, 0) NULL,
	[PD_DAILY_OIL_EXEMPT_ALLOW] [decimal](16, 0) NULL,
	[PD_DAILY_CSH_PRORATED_ALLOW] [decimal](16, 0) NULL,
	[PD_DAILY_CSH_EXEMPT_ALLOW] [decimal](16, 0) NULL,
	[PD_OIL_ALLOWABLE_CYCLE_BBLS] [decimal](16, 0) NULL,
	[PD_CSH_LIMIT_CYCLE_MCF] [decimal](16, 0) NULL,
	[PD_OIL_ALLOW_EFF_YEAR] [int] NULL,
	[PD_OIL_ALLOW_EFF_MONTH] [int] NULL,
	[PD_OIL_ALLOW_EFF_DAY] [int] NULL,
	[PD_OIL_ALLOW_ISS_YEAR] [int] NULL,
	[PD_OIL_ALLOW_ISS_MONTH] [int] NULL,
	[PD_OIL_ALLOW_ISS_DAY] [int] NULL,
	[PD_OIL_ENDING_BALANCE] [decimal](16, 0) NULL,
	[PD_PRESENT_OIL_STATUS] [decimal](16, 0) NULL,
	[PD_PRESENT_CSGHD_STATUS] [decimal](16, 0) NULL,
	[PD_ADJUSTED_OIL_STATUS] [decimal](16, 0) NULL,
	[PD_ADJUSTED_CSGHD_STATUS] [decimal](16, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDREMARK](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_REMARK_NUMBER] [int] NOT NULL,
	[PD_REMARK_LINE_NO] [int] NOT NULL,
	[PD_REMARK_TEXT] [varchar](70) NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDROOT_OIL](
	[RRC_TAPE_RECORD_ID] [char](2) NOT NULL,
	[PD_OIL_CODE] [char](1) NOT NULL,
	[PD_OIL_DISTRICT] [int] NOT NULL,
	[PD_OIL_LEASE_NBR] [int] NOT NULL,
	[PD_MOVABLE_BALANCE] [decimal](20, 0) NULL,
	[PD_BEGINNING_OIL_STATUS] [decimal](20, 0) NULL,
	[PD_BEGINNING_CSGHD_STATUS] [decimal](20, 0) NULL,
	[PD_OIL_OLDEST_EOM_BALANCE] [decimal](20, 0) NULL
) ON [PRIMARY]
GO
ALTER DATABASE [EBCDIC] SET  READ_WRITE 
GO
